project_id = "jamywhzmeizbbobiuhcn"

[functions.generate-recipes]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.zpay-webhook]
verify_jwt = false

[functions.auto-create-accounts]
verify_jwt = false

[functions.create-bulk-accounts]
verify_jwt = false