// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jamywhzmeizbbobiuhcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbXl3aHptZWl6YmJvYml1aGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODkwNTEsImV4cCI6MjA2ODI2NTA1MX0.5Ho6ehKWeAzpjhVhgtVqfIJGCEW2Kv1k7JgX3L1JtdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});